import type { Campus, Lesson } from "./model";
export function seedCampus(): Campus {
  const day = (n: number, h = 18) => {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() + n);
    d.setUTCHours(h, 0, 0, 0);
    return d.toISOString();
  };
  const lesson = (
    id: string,
    title: string,
    track: "devops" | "kids",
    module: string,
    minutes: number,
    explanation: string,
    task: string,
    criteria: string,
    resource = "",
  ): Lesson => ({
    id,
    title,
    track,
    module,
    minutes,
    level: "Débutant",
    explanation,
    task,
    criteria,
    resource,
  });
  return {
    schema: 1,
    students: [
      {
        id: "alex",
        name: "Alex Martin",
        track: "devops",
        email: "alex@example.test",
        parent: "",
        credits: 4,
        active: true,
      },
      {
        id: "samira",
        name: "Samira Diallo",
        track: "devops",
        email: "samira@example.test",
        parent: "",
        credits: 2,
        active: true,
      },
      {
        id: "lucas",
        name: "Lucas Bernard",
        track: "devops",
        email: "lucas@example.test",
        parent: "",
        credits: 1,
        active: true,
      },
      {
        id: "maya",
        name: "Maya Martin",
        track: "kids",
        email: "",
        parent: "Camille Martin",
        credits: 0,
        active: true,
      },
      {
        id: "noah",
        name: "Noah Wilson",
        track: "kids",
        email: "",
        parent: "Jordan Wilson",
        credits: 0,
        active: true,
      },
      {
        id: "ines",
        name: "Inès Mboa",
        track: "kids",
        email: "",
        parent: "Ariane Mboa",
        credits: 0,
        active: true,
      },
    ],
    lessons: [
      lesson(
        "linux-1",
        "Se repérer dans un serveur Linux",
        "devops",
        "01 · Les fondations Linux",
        25,
        "Un serveur est un ordinateur qui rend un service : afficher un site, garder des fichiers ou exécuter une application. Linux organise son travail. Imagine un immeuble : les dossiers sont les pièces, les fichiers sont les objets. Le terminal te permet de demander où tu es et ce qui se trouve autour de toi.\n\npwd affiche le dossier actuel. ls montre son contenu. cd change de dossier. ~ représente ton dossier personnel. Dans un vrai poste DevOps, tu utilises ces repères pour retrouver une configuration ou les journaux d’une application.",
        "Dans ton environnement de pratique autorisé :\n1. Affiche ton emplacement avec pwd.\n2. Crée un dossier avec mkdir -p ~/lessgooo-lab/notes.\n3. Entre avec cd ~/lessgooo-lab/notes.\n4. Vérifie avec pwd puis ls -la.\n5. Explique la différence entre un chemin absolu et un chemin relatif.",
        "Remets les commandes utilisées et leur résultat. Explique pourquoi cd change l’emplacement et ls ne le change pas.",
      ),
      lesson(
        "linux-2",
        "Protéger un dossier avec les permissions",
        "devops",
        "01 · Les fondations Linux",
        35,
        "Une permission est une autorisation. Comme des clés, les droits décident qui entre et ce qu’il peut faire. Linux distingue le propriétaire, le groupe et les autres. Sur un fichier, r permet de lire, w de modifier, x d’exécuter. Sur un dossier, x permet de traverser et w de changer ses entrées avec les droits nécessaires.\n\nAvant de changer les droits, regarde le propriétaire et le besoin réel. Donner tous les droits à tout le monde peut exposer des fichiers.",
        "Dans ~/lessgooo-lab uniquement :\n1. Crée un fichier notes.txt avec un texte sans donnée personnelle.\n2. Inspecte avec ls -l notes.txt.\n3. Exécute chmod 600 notes.txt.\n4. Inspecte de nouveau.\n5. Explique qui peut lire et modifier ce fichier.",
        "Le fichier est accessible en lecture et écriture au propriétaire. Explique les trois groupes de droits sans recourir à chmod 777.",
      ),
      lesson(
        "linux-3",
        "Diagnostiquer un service arrêté",
        "devops",
        "02 · Résoudre un incident",
        40,
        "Imagine un restaurant : le bâtiment peut être ouvert alors que la cuisine est arrêtée. Un serveur peut fonctionner mais son service web peut être indisponible. Le processus est le programme en cours. systemd peut démarrer et surveiller certains services. journalctl consulte les événements enregistrés.\n\nLa démarche : observer le symptôme, rechercher des indices, choisir une correction puis vérifier. Redémarrer sans comprendre peut seulement masquer le problème.",
        "Sur le serveur de laboratoire validé par ton professeur :\n1. Choisis avec lui un service de démonstration.\n2. Lis son état avec systemctl status NOM.\n3. Consulte journalctl -u NOM -n 30 --no-pager.\n4. Note un indice, une hypothèse et une vérification.\nAucune interruption sur un serveur partagé sans autorisation.",
        "Remets une fiche : symptôme, indice, hypothèse, action autorisée et preuve du résultat.",
      ),
      lesson(
        "aws-1",
        "Comprendre le cloud et une instance EC2",
        "devops",
        "03 · AWS & Cloud",
        30,
        "Le cloud consiste à utiliser des ressources informatiques fournies à distance. Au lieu d’acheter ton serveur, tu peux louer une machine virtuelle. Sur AWS, EC2 permet de lancer ces machines. Une région indique une zone géographique ; une instance est une machine virtuelle configurée.\n\nLes ressources peuvent coûter de l’argent même quand tu ne les regardes pas. Une alerte budgétaire avertit ; elle ne garantit pas l’arrêt de toutes les dépenses.",
        "Sans créer de ressource payante :\n1. Dessine le trajet navigateur → Internet → serveur.\n2. Explique le rôle d’une instance EC2.\n3. Écris trois points à vérifier avant un laboratoire : compte autorisé, coût, nettoyage.\n4. Présente ton dessin pendant Zoom.",
        "Distingue ordinateur local, serveur distant et fournisseur cloud. Identifie qui est responsable du compte et du coût.",
      ),
      lesson(
        "git-1",
        "Garder une trace avec Git",
        "devops",
        "04 · Automatiser avec confiance",
        30,
        "Git garde des versions de fichiers dans un dépôt. Un commit est un point enregistré avec une explication. Cela aide une équipe à comprendre une modification et à revenir à un état antérieur. GitHub peut héberger des dépôts Git.\n\nUn secret comme une clé AWS ne doit pas entrer dans l’historique : le supprimer du dernier fichier ne suffit pas à le retirer des anciennes versions.",
        "Dans un nouveau dossier de laboratoire : initialise un dépôt, crée README.md, regarde git status, ajoute le fichier et crée un commit. Modifie une phrase et observe git diff. Utilise uniquement des données fictives.",
        "Remets une capture de git log --oneline et explique ce que contient ton commit.",
      ),
      lesson(
        "kids-1",
        "Mon ordinateur et mes dossiers",
        "kids",
        "01 · Explorer l’informatique",
        20,
        "Ton ordinateur garde tes créations dans des fichiers. Un dossier ressemble à une boîte où tu ranges ces fichiers. Un nom clair te permet de retrouver ton travail. Le navigateur ouvre des pages Internet ; il ne représente pas tout ton ordinateur.",
        "Crée un dossier Mes projets LessGooo. Ajoute deux sous-dossiers : Dessins et Scratch. Crée un petit dessin et range-le dans Dessins. Demande de l’aide si nécessaire.",
        "Montre où est ton dessin et explique la différence entre fichier et dossier.",
      ),
      lesson(
        "scratch-1",
        "Faire bouger mon premier personnage",
        "kids",
        "02 · Créer avec Scratch",
        30,
        "Dans Scratch, tu donnes des instructions avec des blocs. Un événement dit quand commencer : par exemple « quand le drapeau vert est cliqué ». Une séquence est un groupe d’instructions dans un ordre précis.\n\nImagine une recette : d’abord tu commences, ensuite tu fais avancer le personnage, puis tu lui fais dire bonjour. L’ordre change le résultat.",
        "1. Dans Scratch, choisis un personnage.\n2. Ajoute « quand le drapeau vert est cliqué ».\n3. Ajoute « avancer de 10 pas ».\n4. Ajoute « dire Bonjour pendant 2 secondes ».\n5. Change le nombre de pas et observe.\nEnregistre ton fichier .sb3 sur ton ordinateur.",
        "Remets ton fichier Scratch. Explique ce qui déclenche le mouvement et modifie le nombre de pas.",
        "https://scratch.mit.edu/projects/editor/",
      ),
      lesson(
        "scratch-2",
        "Répéter une action sans tout recopier",
        "kids",
        "02 · Créer avec Scratch",
        25,
        "Une boucle répète des instructions. Si tu veux que ton personnage avance dix fois, tu peux mettre l’action dans « répéter 10 fois ». C’est comme demander dix applaudissements avec une seule consigne.",
        "Ajoute une boucle répéter 10 fois avec avancer de 10 pas. Compare avec avancer de 100 pas. Ajoute une petite attente dans la boucle et observe la différence.",
        "Présente ton animation et explique ce qui se répète.",
      ),
      lesson(
        "kids-cloud",
        "Où vivent les fichiers sur Internet ?",
        "kids",
        "03 · Linux, AWS & Cloud",
        20,
        "Un serveur est un ordinateur qui aide d’autres ordinateurs. Quand tu ouvres un site, ton appareil demande des informations à un serveur. Le cloud utilise des ordinateurs à distance. Tes fichiers ne sont pas réellement dans les nuages !\n\nLinux est un système qui aide de nombreux serveurs à fonctionner. AWS fournit des services cloud. Ton professeur montrera un exemple ; tu n’as pas besoin d’ouvrir un compte payant.",
        "Dessine ton ordinateur et un serveur distant. Relie-les par Internet. Explique où se trouve un fichier gardé sur ton ordinateur et où pourrait se trouver un fichier consulté en ligne.",
        "Distingue appareil local et serveur distant et décris une demande simple.",
      ),
      lesson(
        "kids-design",
        "Présenter mon projet avec Canva",
        "kids",
        "04 · Créer et expliquer",
        25,
        "Une bonne affiche transmet une idée claire. Le titre dit de quoi on parle, l’image aide à comprendre et quelques phrases expliquent le résultat. Ton professeur accompagne l’utilisation de Canva selon ton âge.",
        "Prépare le nom de ton projet, ce qu’il fait et une capture sans information personnelle. Avec le professeur, organise-les sur une page puis exporte une image.",
        "L’affiche est lisible et tu peux expliquer tes choix.",
      ),
      lesson(
        "kids-ai",
        "Poser une bonne question à une IA",
        "kids",
        "05 · Découvrir l’IA",
        20,
        "Une IA peut produire une réponse utile, mais elle peut aussi inventer ou se tromper. Pense à une aide qui propose des idées : tu vérifies avant de les utiliser. Explique ce que tu veux et garde tes informations personnelles pour toi.",
        "Avec ton professeur : propose une question pour trouver une idée de jeu Scratch. Précise les personnages et les règles. Compare la réponse aux possibilités de Scratch puis choisis une idée réalisable.",
        "Explique un point à vérifier et une information personnelle à ne pas partager.",
      ),
    ],
    sessions: [
      {
        id: "s1",
        title: "Linux · Les permissions en pratique",
        track: "devops",
        start: day(1, 20),
        duration: 90,
        zoom: "",
        replay: "",
        status: "scheduled",
        attendance: {},
      },
      {
        id: "s2",
        title: "Scratch · Mon premier jeu interactif",
        track: "kids",
        start: day(2, 14),
        duration: 60,
        zoom: "",
        replay: "",
        status: "scheduled",
        attendance: {},
      },
      {
        id: "s3",
        title: "AWS · Du PC au serveur cloud",
        track: "devops",
        start: day(4, 20),
        duration: 90,
        zoom: "",
        replay: "",
        status: "scheduled",
        attendance: {},
      },
      {
        id: "s0",
        title: "Linux · Découvrir le terminal",
        track: "devops",
        start: day(-2, 20),
        duration: 90,
        zoom: "",
        replay: "",
        status: "scheduled",
        attendance: { alex: "present", samira: "present", lucas: "absent" },
      },
    ],
    submissions: [
      {
        id: "sub1",
        student: "alex",
        lesson: "linux-1",
        text: "pwd affiche où je suis. ls liste les fichiers. J’ai créé mon dossier de notes et vérifié son chemin. Un chemin absolu commence depuis /, un chemin relatif part du dossier actuel.",
        url: "",
        created: day(-2),
        status: "validated",
        feedback:
          "Les repères sont acquis. Pour la suite, explique les autorisations de ton dossier.",
        level: "autonome",
      },
      {
        id: "sub2",
        student: "samira",
        lesson: "linux-2",
        text: "J’ai utilisé chmod 600 notes.txt. Le propriétaire peut lire et écrire. Le groupe et les autres n’ont aucun droit.",
        url: "",
        created: day(-1),
        status: "pending",
        feedback: "",
        level: "",
      },
      {
        id: "sub3",
        student: "maya",
        lesson: "kids-1",
        text: "J’ai mis mon dessin dans Mes projets LessGooo puis Dessins. Le dossier est la boîte et le fichier est mon dessin.",
        url: "",
        created: day(-1),
        status: "validated",
        feedback:
          "Tu retrouves ton fichier seule. Prochaine mission : créer ton personnage Scratch.",
        level: "autonome",
      },
    ],
    slots: [
      {
        id: "slot1",
        start: day(2, 16),
        duration: 50,
        student: null,
        goal: "",
        status: "open",
        zoom: "",
      },
      {
        id: "slot2",
        start: day(3, 16),
        duration: 50,
        student: null,
        goal: "",
        status: "open",
        zoom: "",
      },
      {
        id: "slot3",
        start: day(5, 17),
        duration: 50,
        student: "samira",
        goal: "Comprendre les permissions Linux",
        status: "booked",
        zoom: "",
      },
    ],
    stages: [
      {
        id: "stage1",
        student: "alex",
        status: "preparation",
        mentor: "",
        start: "",
        end: "",
        notes:
          "Consolider les bases Linux et remettre le projet de diagnostic avant la revue du dossier.",
        activities: [],
      },
      {
        id: "stage2",
        student: "samira",
        status: "submitted",
        mentor: "",
        start: "",
        end: "",
        notes:
          "Dossier fictif utilisé pour tester le suivi. Aucune affectation réelle.",
        activities: [],
      },
    ],
    payments: [
      {
        id: "pay1",
        student: "alex",
        amount: 15000,
        currency: "USD",
        date: day(-5).slice(0, 10),
        reference: "DEMO-001",
        status: "verified",
        description: "Formation DevOps · exemple",
      },
      {
        id: "pay2",
        student: "maya",
        amount: 10000,
        currency: "USD",
        date: day(-4).slice(0, 10),
        reference: "DEMO-002",
        status: "verified",
        description: "LessGooo Kids · exemple",
      },
      {
        id: "pay3",
        student: "samira",
        amount: 15000,
        currency: "USD",
        date: day(-1).slice(0, 10),
        reference: "DEMO-003",
        status: "pending",
        description: "Formation DevOps · exemple",
      },
    ],
    help: [
      {
        id: "help1",
        student: "alex",
        question: "Pourquoi le droit x est-il nécessaire sur un dossier ?",
        answer:
          "Sur un dossier, x permet de le traverser pour accéder à ses éléments. Nous ferons une démonstration pendant Zoom.",
        created: day(-1),
      },
    ],
    audit: [],
  };
}
