import {
  pair as p,
  type SchoolCatalog,
  type Subject,
  type Resource,
} from "./model";
import { chapters } from "./lessons";

const generalSubjects: [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
][] = [
  [
    "math",
    "Mathématiques",
    "Mathematics",
    "Comprendre les nombres, les formes et les raisonnements pour résoudre un problème.",
    "Use numbers, shapes and reasoning to solve problems.",
    "Savoir lire une consigne ; commencer par les opérations et les fractions.",
    "Read instructions; begin with arithmetic and fractions.",
  ],
  [
    "pct",
    "PCT / sciences physiques",
    "Physical sciences",
    "Expliquer le mouvement, l'électricité et les transformations de la matière.",
    "Explain motion, electricity and changes in matter.",
    "Opérations, unités de mesure et règles de sécurité ; aucune expérience électrique sur le secteur.",
    "Arithmetic, units and safety; never experiment with mains electricity.",
  ],
  [
    "french",
    "Français",
    "French",
    "Lire, comprendre, argumenter et écrire avec précision.",
    "Read, understand, argue and write clearly in French.",
    "Alphabet, lecture de phrases simples ; un cahier pour écrire et se corriger.",
    "Alphabet and simple sentence reading; a notebook for writing and corrections.",
  ],
  [
    "english",
    "Anglais",
    "English",
    "Comprendre et communiquer dans des situations quotidiennes et scolaires.",
    "Understand and communicate in everyday and school situations.",
    "Alphabet, vocabulaire courant et envie de pratiquer à voix haute.",
    "Alphabet, everyday vocabulary and willingness to practise aloud.",
  ],
  [
    "svt",
    "SVT / biologie",
    "Biology / life sciences",
    "Comprendre le vivant, la santé et les relations avec l'environnement.",
    "Understand living things, health and the environment.",
    "Lire un schéma, distinguer observation et opinion ; respecter le vivant.",
    "Read a diagram, distinguish observation from opinion and respect living things.",
  ],
  [
    "computing",
    "Informatique",
    "Computer science",
    "Utiliser les outils numériques et décomposer un problème en instructions.",
    "Use digital tools and break a problem into instructions.",
    "Aucun ordinateur obligatoire pour les premiers algorithmes : papier et crayon suffisent.",
    "The first algorithms need only paper and pencil; a computer is optional.",
  ],
  [
    "physics",
    "Physique",
    "Physics",
    "Étudier les forces, l'énergie, les ondes et les circuits.",
    "Study forces, energy, waves and circuits.",
    "Calcul, conversions et lecture de graphiques.",
    "Arithmetic, unit conversion and graph reading.",
  ],
  [
    "chemistry",
    "Chimie",
    "Chemistry",
    "Comprendre les substances et les réactions sans expérience dangereuse à domicile.",
    "Understand substances and reactions without unsafe home experiments.",
    "Proportions, unités et règles de sécurité.",
    "Ratios, units and safety rules.",
  ],
  [
    "history",
    "Histoire",
    "History",
    "Interroger des sources pour comprendre les sociétés dans le temps.",
    "Question sources to understand societies over time.",
    "Lire un texte, situer une date et citer sa source.",
    "Read a text, locate a date and cite a source.",
  ],
  [
    "geography",
    "Géographie",
    "Geography",
    "Lire des cartes et comprendre les territoires et leurs habitants.",
    "Read maps and understand places and their communities.",
    "Repères, échelles et observation de l'environnement.",
    "Directions, scales and observation of the environment.",
  ],
  [
    "civics",
    "Éducation à la citoyenneté",
    "Citizenship education",
    "Comprendre la vie collective, les droits et les responsabilités.",
    "Understand community life, rights and responsibilities.",
    "Écouter, lire une situation et argumenter avec respect.",
    "Listen, read a situation and discuss respectfully.",
  ],
  [
    "literature",
    "Littérature",
    "Literature",
    "Analyser un récit, un poème ou une pièce en s'appuyant sur le texte.",
    "Analyse stories, poems and plays using textual evidence.",
    "Lecture suivie ; vérifier les œuvres prescrites auprès de l'établissement.",
    "Regular reading; check prescribed works with your school.",
  ],
  [
    "philosophy",
    "Philosophie",
    "Philosophy",
    "Clarifier une question et construire une réflexion argumentée.",
    "Clarify a question and build a reasoned argument.",
    "Lecture, définitions précises et distinction entre exemple et preuve.",
    "Reading, precise definitions and distinguishing examples from evidence.",
  ],
  [
    "economics",
    "Économie",
    "Economics",
    "Comprendre les choix, les échanges et l'utilisation de ressources limitées.",
    "Understand choices, trade and the use of limited resources.",
    "Pourcentages, graphiques et vocabulaire de base.",
    "Percentages, graphs and basic vocabulary.",
  ],
  [
    "accounting",
    "Comptabilité",
    "Accounting",
    "Organiser les opérations financières et vérifier des comptes.",
    "Organise financial transactions and check accounts.",
    "Calcul exact, tableaux et méthode.",
    "Accurate arithmetic, tables and an orderly approach.",
  ],
  [
    "commerce",
    "Commerce",
    "Commerce",
    "Comprendre l'achat, la vente et le fonctionnement d'une activité.",
    "Understand buying, selling and business operations.",
    "Lecture, calcul de pourcentages et communication.",
    "Reading, percentages and communication.",
  ],
  [
    "german",
    "Allemand",
    "German",
    "Découvrir une autre langue et communiquer progressivement.",
    "Learn another language and gradually communicate.",
    "Alphabet, écoute et pratique régulière.",
    "Alphabet, listening and regular practice.",
  ],
  [
    "spanish",
    "Espagnol",
    "Spanish",
    "Développer la compréhension et l'expression dans une autre langue.",
    "Develop understanding and expression in another language.",
    "Alphabet, écoute et pratique régulière.",
    "Alphabet, listening and regular practice.",
  ],
  [
    "national-languages",
    "Langues et cultures nationales",
    "National languages and cultures",
    "Découvrir les langues et les pratiques culturelles selon le contexte de l'école.",
    "Explore languages and cultural practices in the school's context.",
    "Préciser la langue et le programme retenus avec l'enseignant.",
    "Agree the language and programme with the teacher.",
  ],
  [
    "home-economics",
    "Économie sociale et familiale",
    "Home economics",
    "Développer des compétences pour la vie quotidienne et la gestion du foyer.",
    "Develop everyday skills and household management.",
    "Lecture de consignes, hygiène et sécurité.",
    "Following instructions, hygiene and safety.",
  ],
  [
    "pe",
    "Éducation physique et sportive",
    "Physical education",
    "Développer la motricité, la coopération et une activité adaptée.",
    "Develop movement, teamwork and suitable physical activity.",
    "Espace sûr, équipement adapté et consignes de l'encadrant.",
    "A safe space, suitable equipment and supervisor instructions.",
  ],
  [
    "technology",
    "Technologie",
    "Technology",
    "Comprendre des objets techniques et concevoir des solutions simples.",
    "Understand technical objects and design simple solutions.",
    "Mesures, schémas et sécurité des outils.",
    "Measurement, diagrams and tool safety.",
  ],
  [
    "arts",
    "Arts et expression",
    "Arts and expression",
    "Observer, créer et expliquer ses choix artistiques.",
    "Observe, create and explain artistic choices.",
    "Papier et outils disponibles ; aucune fourniture coûteuse requise pour commencer.",
    "Paper and available materials; expensive supplies are not needed to start.",
  ],
  [
    "reading",
    "Lecture et écriture",
    "Reading and writing",
    "Reconnaître les sons, lire des mots puis comprendre des textes simples.",
    "Recognise sounds, read words and understand simple texts.",
    "Commencer au niveau réel de l'enfant avec un adulte accompagnateur.",
    "Start at the child's current level with a supporting adult.",
  ],
];
const subjects: Subject[] = generalSubjects.map(
  ([id, fr, en, df, de, pf, pe]) => ({
    id,
    name: p(fr, en),
    description: p(df, de),
    prerequisites: p(pf, pe),
    active: true,
  }),
);
const frClasses = ["6e", "5e", "4e", "3e", "2nde", "1re", "terminale"];
const primaryFR = ["SIL", "CP", "CE1", "CE2", "CM1", "CM2"];
const classes: SchoolCatalog["classes"] = [
  ...primaryFR.map((name) => ({
    id: `fr-${name.toLowerCase()}`,
    name: p(name, name),
    system: "fr" as const,
    cycle: "primary" as const,
    exam: name === "CM2" ? "CEP" : "",
    tuition: null,
    tutoring: false,
    active: true,
  })),
  ...Array.from({ length: 6 }, (_, i) => ({
    id: `en-class${i + 1}`,
    name: p(`Class ${i + 1}`, `Class ${i + 1}`),
    system: "en" as const,
    cycle: "primary" as const,
    exam: i === 5 ? "FSLC" : "",
    tuition: null,
    tutoring: false,
    active: true,
  })),
  ...frClasses.map((name, i) => ({
    id: `fr-${name}`,
    name: p(
      name === "terminale" ? "Terminale" : name,
      name === "terminale" ? "Terminale" : name,
    ),
    system: "fr" as const,
    cycle: "secondary" as const,
    exam:
      i === 3 ? "BEPC" : i === 5 ? "Probatoire" : i === 6 ? "Baccalauréat" : "",
    tuition: i < 2 ? null : i < 5 ? 5000 : 10000,
    tutoring: i >= 2,
    active: true,
  })),
  ...[
    "Form 1",
    "Form 2",
    "Form 3",
    "Form 4",
    "Form 5",
    "Lower Sixth",
    "Upper Sixth",
  ].map((name, i) => ({
    id: `en-${i + 1}`,
    name: p(name, name),
    system: "en" as const,
    cycle: "secondary" as const,
    exam: i === 4 ? "GCE O Level" : i === 6 ? "GCE A Level" : "",
    tuition: null,
    tutoring: false,
    active: true,
  })),
];
const resource = (
  id: string,
  fr: string,
  en: string,
  kind: Resource["kind"],
  url: string,
  source: string,
  description: ReturnType<typeof p>,
  extra: Partial<Resource> = {},
): Resource => ({
  id,
  title: p(fr, en),
  kind,
  url,
  mediaId: "",
  source,
  description,
  classIds: [],
  subjectId: "",
  year: "",
  language: "both",
  status: "source",
  rights: p(
    "Consulter sur le site source. Redistribution non autorisée par ce lien.",
    "Read on the source website. This link does not grant redistribution rights.",
  ),
  published: true,
  ...extra,
});
const resources: Resource[] = [
  resource(
    "programmes",
    "Programmes officiels du secondaire",
    "Official secondary curricula",
    "programme",
    "https://www.minesec.gov.cm/web/index.php/fr/systeme-educatif/progammes-officiels",
    "MINESEC",
    p(
      "Enseignement général, technique et formation des enseignants, dans les deux sous-systèmes. Vérifiez la classe, la série et l'édition du document.",
      "General, technical and teacher education in both subsystems. Check the class, stream and document edition.",
    ),
  ),
  resource(
    "manuals",
    "Listes de manuels : vérifier l'année",
    "Textbook lists: check the year",
    "booklist",
    "https://www.minesec.gov.cm/web/index.php/fr/systeme-educatif/manuels-scolaires",
    "MINESEC",
    p(
      "La page consultée affiche notamment 2023–2024 et des éditions antérieures. Faites confirmer la liste actuelle par votre établissement avant tout achat.",
      "The page consulted includes 2023–2024 and older editions. Ask your school to confirm the current list before buying.",
    ),
    { year: "2023–2024", status: "historical" },
  ),
  resource(
    "primary",
    "Ressources officielles du primaire",
    "Official primary education resources",
    "programme",
    "https://www.minedub.cm/",
    "MINEDUB",
    p(
      "Point d'entrée du ministère pour le primaire. Vérifiez les listes de manuels et les publications de l'année scolaire.",
      "Ministry entry point for primary education. Check textbook lists and publications for the relevant school year.",
    ),
  ),
  resource(
    "distance",
    "Cours à distance : choisir sa classe",
    "Distance learning: choose your class",
    "video",
    "https://minesec-distance.schoolfaqs.net/",
    "Portail MINESEC Distance Education / Schoolfaqs",
    p(
      "Rechercher par sous-système, cycle, classe et matière. La disponibilité des leçons et vidéos varie ; certaines rubriques sont encore vides.",
      "Browse by subsystem, cycle, class and subject. Lesson and video availability varies; some sections are still empty.",
    ),
  ),
  resource(
    "papers",
    "Collections d'annales et examens blancs",
    "Past-paper and mock-exam collections",
    "paper",
    "https://minesec-distance.schoolfaqs.net/revision",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Sélectionner l'examen puis la matière. Les examens blancs sont des entraînements ; la collection ne garantit pas toutes les sessions.",
      "Select an exam and subject. Mock exams are practice papers; the collection does not guarantee every session.",
    ),
  ),
  resource(
    "bepc",
    "BEPC : collection de sujets",
    "BEPC: paper collection",
    "paper",
    "https://minesec-distance.schoolfaqs.net/revision/bepc",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Annales classées par matière. Vérifier l'année et la présence d'un corrigé sur la source.",
      "Papers organised by subject. Check the year and whether a solution is available at the source.",
    ),
    { classIds: ["fr-3e"] },
  ),
  resource(
    "ol",
    "GCE O Level : collection de sujets",
    "GCE O Level: paper collection",
    "paper",
    "https://minesec-distance.schoolfaqs.net/revision/gce-ordinary-level",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Entraînement par matière, à confronter au syllabus de la session visée.",
      "Subject practice to compare with the syllabus for your examination session.",
    ),
    { classIds: ["en-5"] },
  ),
  resource(
    "al",
    "GCE A Level : collection de sujets",
    "GCE A Level: paper collection",
    "paper",
    "https://minesec-distance.schoolfaqs.net/revision/gce-advanced-level",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Annales par matière ; vérifier les options et la session.",
      "Subject papers; check options and the examination session.",
    ),
    { classIds: ["en-6", "en-7"] },
  ),
  resource(
    "proba",
    "Probatoire : examens blancs",
    "Probatoire: mock examinations",
    "mock",
    "https://minesec-distance.schoolfaqs.net/revision/probatoire-examen-blanc",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Sujets d'entraînement, distincts des sujets officiels du Probatoire.",
      "Practice papers, separate from official Probatoire examination papers.",
    ),
    { classIds: ["fr-1re"] },
  ),
  resource(
    "bac",
    "Baccalauréat : examens blancs",
    "Baccalaureate: mock examinations",
    "mock",
    "https://minesec-distance.schoolfaqs.net/revision/baccalaureat-blanc",
    "MINESEC Distance Education / Schoolfaqs",
    p(
      "Entraînements à utiliser avec les programmes et consignes officiels.",
      "Practice papers to use alongside official curricula and instructions.",
    ),
    { classIds: ["fr-terminale"] },
  ),
  resource(
    "gce-calendar",
    "Calendriers officiels GCE / TVEE",
    "Official GCE / TVEE timetables",
    "document",
    "https://camgceb.org/examinations/timetables/",
    "Cameroon GCE Board",
    p(
      "Les publications consultées concernent 2026. Vérifiez toute nouvelle session ; ce n'est pas l'emploi du temps des répétitions.",
      "Publications consulted concern 2026. Check for the new session; this is separate from the tutoring timetable.",
    ),
    { year: "2026", status: "historical", language: "en" },
  ),
  resource(
    "obc",
    "Office du baccalauréat : informations officielles",
    "Baccalaureate office: official information",
    "document",
    "https://officedubac.cm/",
    "Office du baccalauréat du Cameroun",
    p(
      "Actualités, calendriers et informations d'examens. Toujours vérifier la date du document.",
      "News, calendars and examination information. Always check the document date.",
    ),
  ),
  resource(
    "school-calendar",
    "Calendrier scolaire 2026–2027",
    "2026–2027 school calendar",
    "document",
    "https://officedubac.cm/wp-content/uploads/2026/09/Calendrier-Scolaire-Cameroun-2026-2027.pdf",
    "Office du baccalauréat du Cameroun",
    p(
      "Document publié sur le site de l'OBC. Se référer au texte pour les périodes et exceptions ; les cours LESSGOOO ont leurs propres créneaux.",
      "Document published on the OBC website. Read it for periods and exceptions; LESSGOOO tutoring has its own time slots.",
    ),
    { year: "2026–2027" },
  ),
  resource(
    "nrich",
    "Défis mathématiques : raisonner et expliquer",
    "Mathematical challenges: reason and explain",
    "exercise",
    "https://nrich.maths.org/students/secondary",
    "NRICH — University of Cambridge",
    p(
      "Problèmes ouverts pour dépasser les automatismes. Choisir un thème puis écrire une justification, même sans trouver immédiatement.",
      "Open problems that go beyond routine work. Pick a topic and explain your reasoning, even without an immediate solution.",
    ),
    { subjectId: "math", status: "complement", language: "en" },
  ),
  resource(
    "olympiad",
    "Défis avancés : olympiades internationales",
    "Advanced challenges: International Mathematical Olympiad",
    "exercise",
    "https://www.imo-official.org/problems/",
    "International Mathematical Olympiad",
    p(
      "Niveau très avancé. Travailler les prérequis, chercher plusieurs approches et demander un retour à l'enseignant.",
      "Very advanced level. Build prerequisites, try several approaches and ask a teacher for feedback.",
    ),
    { subjectId: "math", status: "complement", language: "en" },
  ),
  resource(
    "phet",
    "Laboratoire virtuel de sciences",
    "Virtual science laboratory",
    "simulation",
    "https://phet.colorado.edu/fr/",
    "PhET — University of Colorado Boulder",
    p(
      "Simulations de sciences et mathématiques. Prédire, tester puis expliquer l'observation ; vérifier la langue et le fonctionnement hors ligne.",
      "Science and mathematics simulations. Predict, test and explain observations; check language and offline availability.",
    ),
    { subjectId: "pct", status: "complement" },
  ),
  resource(
    "bc",
    "Anglais : écouter, lire, écrire",
    "English: listen, read and write",
    "exercise",
    "https://learnenglishteens.britishcouncil.org/skills",
    "British Council",
    p(
      "Exercices par compétence et niveau avec supports audio ou vidéo selon l'activité.",
      "Skills and level-based practice with audio or video depending on the activity.",
    ),
    { subjectId: "english", status: "complement", language: "en" },
  ),
  resource(
    "tv5",
    "Français : exercices avec vidéos",
    "French: video-based exercises",
    "video",
    "https://apprendre.tv5monde.com/fr",
    "TV5MONDE",
    p(
      "Compréhension du français par niveaux. Complément linguistique, pas une liste d'œuvres au programme camerounais.",
      "Level-based French comprehension. Language enrichment, not a list of prescribed Cameroonian literary works.",
    ),
    { subjectId: "french", status: "complement", language: "fr" },
  ),
  resource(
    "ioi",
    "Algorithmique : exercices progressifs",
    "Algorithms: progressive exercises",
    "exercise",
    "https://www.france-ioi.org/algo/course.php?iOrder=20&idChapter=811",
    "France-IOI",
    p(
      "S'entraîner à décomposer un problème et vérifier son programme. Certaines activités peuvent demander un compte sur le site source.",
      "Practise decomposing a problem and checking your program. Some activities may require an account on the source site.",
    ),
    { subjectId: "computing", status: "complement", language: "fr" },
  ),
  resource(
    "minesup",
    "Études supérieures : s'informer à la source",
    "Higher education: consult official information",
    "guidance",
    "https://www.minesup.gov.cm/",
    "MINESUP",
    p(
      "Vérifier l'établissement, les filières, les conditions d'admission et les publications officielles avant de candidater.",
      "Check the institution, courses, entry requirements and official publications before applying.",
    ),
  ),
];

export const initialCatalog: SchoolCatalog = {
  schema: 1,
  schoolYear: "2026–2027",
  registration: 2000,
  tutoringSubjectIds: ["math", "pct", "french", "english", "svt", "computing"],
  billing: "unknown",
  timezone: "Africa/Douala",
  availability: [
    ...[1, 2, 3, 4, 5].map((day) => ({ day, start: "16:00", end: "18:00" })),
    { day: 6, start: "08:00", end: "12:00" },
  ],
  classes,
  subjects,
  chapters,
  resources,
  timetable: [],
};
